require: 
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0
  Exclude:
   - 'app/views/**/*'
   - 'db/**/*'
   - 'docs/**/*'
   - 'vendor/bundle/**/*'
   - 'bin/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 50

Style/Documentation:
  Enabled: false