version: '3'

services:
  ipa-toolkit-backend:
    container_name: ipa-toolkit-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.0-bullseye"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace
      - bundle:/usr/local/bundle
    command: sleep infinity
    depends_on:
      - ipa-toolkit-backend-postgres
      - ipa-toolkit-backend-mailcatcher
    environment:
      API_ORIGIN: localhost:3001
      DEFAULT_HOST: localhost:3000
      LANG: C.UTF-8
      RAILS_ENV: development
      DATABASE_URL: "postgresql://postgres:secret@ipa-toolkit-backend-postgres/ipa-toolkit_development"
      SYSTEM_EMAIL_ADDRESS: system@ipa-toolkit
    networks:
      - ipa-toolkit-network
      - ipa-toolkit-backend-network

  ipa-toolkit-backend-postgres:
    container_name: ipa-toolkit-backend-postgres
    image: postgres:13.2-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "secret"
    networks:
      - ipa-toolkit-backend-network

  ipa-toolkit-backend-mailcatcher:
    container_name: ipa-toolkit-backend-mailcatcher
    image: tophfr/mailcatcher:0.7.1
    ports:
     - '3080:80'
    networks:
      - ipa-toolkit-backend-network

networks:
  ipa-toolkit-backend-network:
  ipa-toolkit-network:
    external: true

volumes:
  bundle:
  database:
